### ISSUE TITLE
Убрать скрытие "Места" при разрешении меньше 480px

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/olympic#22]
На главной странице поле "место" скрывается при разрешении меньше, чем 480px и страницы выглядит не эстетично.
![screenshot_89](https://cloud.githubusercontent.com/assets/9131239/23857254/66d64f80-0848-11e7-889e-7659edaf8f65.png)

**Comment by danilenkodanila** [comment]
<img width="629" alt="2017-03-14 0 30 08" src="https://cloud.githubusercontent.com/assets/10443020/23858811/6d3afce0-084d-11e7-976b-ecbdae82049c.png">

**Comment by bezgodov** [comment]
@danilenkodanila Спасибо, исправлено!
