### ISSUE TITLE
Заполнить блоки на главной информацией

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/olympic#4]
В каждом блоке не выводится вся информация [убрать пустое пространство или выводить какую-либо информацию]
![screenshot_62](https://cloud.githubusercontent.com/assets/9131239/23842149/f667fe82-07fd-11e7-8364-bf534aa557a1.png)

**Comment by danilenkodanila** [comment]
<img width="121" alt="2017-03-14 0 32 19" src="https://cloud.githubusercontent.com/assets/10443020/23858888/b4605692-084d-11e7-8728-ea266872cee7.png">

**Comment by bezgodov** [comment]
@danilenkodanila Спасибо, исправлено!
