### ISSUE TITLE
Внутрення страница мероприятия слишком однотипна

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/olympic#7]
Используется много синего цвета, необходимо сделать новую компоновку цветов
![screenshot_65](https://cloud.githubusercontent.com/assets/9131239/23842268/c473a772-07fe-11e7-89a7-fb68648391ca.png)

**Comment by danilenkodanila** [comment]
<img width="258" alt="2017-03-14 0 31 23" src="https://cloud.githubusercontent.com/assets/10443020/23858845/9113b33c-084d-11e7-8e30-825dd13b2251.png">

**Comment by bezgodov** [comment]
@danilenkodanila Спасибо, исправлено!
